// File generated by Antigravity (Dummy placeholder)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAQcEtxYRDsKnwVGrqoNbL5y9XNn7EWc',
    appId: '1:146070702348:web:10513e74a06bfe52252129',
    messagingSenderId: '146070702348',
    projectId: 'interioe-design-app',
    authDomain: 'interioe-design-app.firebaseapp.com',
    storageBucket: 'interioe-design-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTX842qirf5J2gdGv_deisDKglT6EE3p4',
    appId: '1:146070702348:android:81043f119e8a8059252129',
    messagingSenderId: '146070702348',
    projectId: 'interioe-design-app',
    storageBucket: 'interioe-design-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5mvLxjCZYPggGLOlMTjQsd0aiz6qsWU',
    appId: '1:146070702348:ios:2bd6c27ae29262e1252129',
    messagingSenderId: '146070702348',
    projectId: 'interioe-design-app',
    storageBucket: 'interioe-design-app.firebasestorage.app',
    iosBundleId: 'com.example.interiorDesignApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSB8AyU3vyhV7XCCxEEIc1kXWw-nuVlgc',
    appId: '1:155765340966:ios:c372cbb2ae3f323dc01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    storageBucket: 'real-estate-owner.firebasestorage.app',
    androidClientId: '155765340966-ifklbvu25v8vols0toep1aoek9nnhbcj.apps.googleusercontent.com',
    iosClientId: '155765340966-k3949dqd08ctosev5c5b0uvkdfatjs2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstateOwnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxN6pNWxp_W4oSGaCAT12lArZW3UkvMHM',
    appId: '1:155765340966:web:0085f961f0d03d7ec01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    authDomain: 'real-estate-owner.firebaseapp.com',
    storageBucket: 'real-estate-owner.firebasestorage.app',
  );

}